### ISSUE TITLE
<CHARNAME> mentioning in candlekeeptot.tra.

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahToT#2]
Hi, I think the episode in Candlekeep is happening when <CHARNAME> is already Midnight, is it ok to have <CHARNAME> in this file?

**Comment by RoxanneSHS** [comment]
Yes, it works correctly in game. The reference is changed during the transition from RtF to ToT when the player character and Sandrah are exchanged and Midnight is created.
I just tested it again in my game because I thought that maybe you found a bug but it works as it should.

**Comment by abalabokhin** [comment]
Ok, sorry for that, it was the only tra file where somebody addressed Midnight as <CHARNAME> that made me suspicious.

**Comment by RoxanneSHS** [comment]
That is the traditional error of Charname = Player 1. Which is true in the standard game at all times...but technically in ToT, Player1 is actually....Pelligram (You can see it when Haiass starts to follow her after the transition). 
Midnight can be any Player2 to 6, it depends on what Sandrah was before and how many/which other NPCs you had during the whole game since you left Candlekeep. There is about an 80 per cent chance that Midnight = Player2 in ToT.
